Repository CSC207-2022F-UofT/course-project-todo-find-a-team-name, pull requests merged in 2022-12, with the labels that each got.

#65 Major error in isconflicted method in section entity
  src/main/java/entities/Block.java
  src/main/java/entities/Section.java
  src/test/java/entities/BlockTest.java
  src/test/java/entities/SectionTest.java
Labels: bug

#76 7 feature 7 blacklistwhitelist domenttest
  src/main/java/blacklist_whitelist_use_case/application_business/SectionFilterInputBoundary.java
  src/main/java/blacklist_whitelist_use_case/application_business/SectionFilterInteractor.java
  src/main/java/blacklist_whitelist_use_case/application_business/SectionFilterOutputBoundary.java
  src/main/java/blacklist_whitelist_use_case/application_business/SectionFilterRequestModel.java
  src/main/java/blacklist_whitelist_use_case/application_business/SectionFilterResponseModel.java
  src/main/java/blacklist_whitelist_use_case/application_business/removeLater.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/ConstraintsInputScreen.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/CourseCodePanel.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/DayConstraintsPanel.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/FilteredSectionsOutputScreen.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/HelpInstructionScreen.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/LabelComboBoxTextField.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/TimeConstraintsPanel.java
  src/main/java/blacklist_whitelist_use_case/frameworks_and_drivers/removeLater.java
  src/main/java/blacklist_whitelist_use_case/interface_adapters/ISectionFilterView.java
  src/main/java/blacklist_whitelist_use_case/interface_adapters/SectionFilterController.java
  src/main/java/blacklist_whitelist_use_case/interface_adapters/SectionFilterPresenter.java
  src/main/java/blacklist_whitelist_use_case/interface_adapters/SectionFilterViewModel.java
  src/main/java/blacklist_whitelist_use_case/interface_adapters/removeLater.java
  src/main/java/edit_timetable_use_case/application_business/AddCourseInteractor.java
  src/main/java/edit_timetable_use_case/application_business/EditCourseInteractor.java
  src/main/java/entities/RoomConstraint.java
  src/main/java/entities/TimeIntervalConstraint.java
  src/main/java/entities/Timetable.java
  src/main/java/entities/WeekdayConstraint.java
  src/main/java/screens/AllTimetablesScreen.java
  src/main/java/screens/ConstraintsInputScreen.java
  src/main/java/screens/MainUI.java
  src/main/java/screens/SectionFilterController.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorInputBoundary.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorInteractor.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorOutputBoundary.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorRequestModel.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorResponseModel.java
  src/main/java/timetable_generator_use_case/frameworks_and_drivers/GenerateTimetableScreen.java
  src/main/java/timetable_generator_use_case/interface_adapters/TimetableGeneratorController.java
  src/main/java/timetable_generator_use_case/interface_adapters/TimetableGeneratorPresenter.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortInputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortInteractor.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortOutputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortRequestModel.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortResponseModel.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/AllTimetablesScreen.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/TimetablesSortMenu.java
  src/main/java/timetables_sort_use_case/interface_adapters/AllTimetablesView.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortController.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortPresenter.java
  src/test/java/blacklist_whitelist_use_case/SectionFilterControllerTest.java
  src/test/java/blacklist_whitelist_use_case/SectionFilterInteractorTest.java
  src/test/java/blacklist_whitelist_use_case/SectionFilterPresenterTest.java
  src/test/java/entities/TimeIntervalConstraintTest.java
  src/test/java/entities/TimetableTest.java
  src/test/java/timetable_generator_use_case/TimeTableGeneratorTest.java
Labels: enhancement

#78 Feature 11 finish timetable course generator
  src/main/java/generate_timetable_course_use_case/application_business/TimetableCourseGenerator.java
  src/main/java/generate_timetable_course_use_case/application_business/removeLater.java
  src/main/java/generate_timetable_course_use_case/frameworks_and_drivers/removeLater.java
  src/main/java/generate_timetable_course_use_case/interface_adapters/removeLater.java
  src/main/java/recommend_br_use_case/application_business/BRRecommender.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorInteractor.java
  src/test/java/generate_timetable_course_use_case/TimetableCourseGeneratorTest.java
Labels: enhancement

#82 Feature 5 breadth requirement recommendation fix minor errors
  src/main/java/recommend_br_use_case/application_business/BRRecommender.java
  src/main/java/recommend_br_use_case/frameworks_and_drivers/RecommendBROutputScreen.java
  src/main/java/recommend_br_use_case/interface_adapters/RecommendBRPresenter.java
Labels: bug

#86 Feature 3 overlapping shenanigans
  src/main/java/display_timetable_use_case/frameworks_and_drivers/TimetableUI.java
  src/main/java/display_timetable_use_case/frameworks_and_drivers/TimetableView.java
  src/main/java/entities/Block.java
  src/main/java/entities/Course.java
  src/main/java/entities/Section.java
  src/main/java/entities/Session.java
  src/main/java/entities/Timetable.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/CalculateSectionHoursInteractor.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/OverlapGeneratedTimetableRelayInteractor.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/OverlapOutputBoundary.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/SectionHoursInputBoundary.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/TimeTableMatchInteractor.java
  src/main/java/generate_overlapping_timetable_use_case/application_business/TimetableMatchInputBoundary.java
  src/main/java/generate_overlapping_timetable_use_case/frameworks_and_drivers/OverlapInputDialog.form
  src/main/java/generate_overlapping_timetable_use_case/frameworks_and_drivers/OverlapInputDialog.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/ModelToOverlapViewModelConverter.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapInputView.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapMaxPresenter.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapMaximizationController.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapTimetableBlockViewModel.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapTimetableCourseViewModel.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapTimetableSectionViewModel.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapTimetableViewModel.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/OverlapTimetableViewModelToModelConverter.java
  src/main/java/generate_overlapping_timetable_use_case/interface_adapters/TimetableModelUnpacker.java
  src/main/java/generate_timetable_course_use_case/application_business/TimetableCourseGenerator.java
  src/main/java/overlap_crap_fix_locations_later/InputBoundaries/OverlapMaxInputBoundary.java
  src/main/java/overlap_crap_fix_locations_later/InputBoundaries/SectionHoursInputBoundary.java
  src/main/java/overlap_crap_fix_locations_later/InputBoundaries/TimetableMatchInputBoundary.java
  src/main/java/overlap_crap_fix_locations_later/OverlapInputDialog.java
  src/main/java/overlap_crap_fix_locations_later/OverlapInputDialogDataKeys.java
  src/main/java/overlap_crap_fix_locations_later/OverlapMaximizationController.java
  src/main/java/overlap_crap_fix_locations_later/tests/TestCalculateSectionHoursInteractor.java
  src/main/java/overlap_crap_fix_locations_later/tests/TestTimeTableMatchInteractor.java
  src/main/java/screens/MainUI.java
  src/main/java/timetable_generator_use_case/application_business/TimetableGeneratorInteractor.java
  src/main/java/timetables_sort_use_case/application_business/AllTimetablesInputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/AllTimetablesPublisher.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortInteractor.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/AllTimetablesScreen.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/TimetablesSortMenu.java
  src/main/java/timetables_sort_use_case/interface_adapters/AllTimetablesController.java
  src/main/java/timetables_sort_use_case/interface_adapters/AllTimetablesView.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortController.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortPresenter.java
  src/main/resources/strings
  src/main/resources/strings.properties
  src/test/java/overlap_maximization_use_case/TestCalculateSectionHoursInteractor.java
  src/test/java/overlap_maximization_use_case/TestModelToOverlapViewModelConverter.java
  src/test/java/overlap_maximization_use_case/TestOverlapMaximizationController.java
  src/test/java/overlap_maximization_use_case/TestOverlapTimetableViewModelToModelConverter.java
  src/test/java/overlap_maximization_use_case/TestTimeTableMatchInteractor.java
  src/test/java/overlap_maximization_use_case/TestTimetableModelUnpacker.java
  src/test/java/overlap_stuff_fix_layout_later/OverlapInputDialogTest.java
  src/test/java/timetables_sort_use_case/application_business/AllTimetablesInteractorTest.java
  src/test/java/timetables_sort_use_case/application_business/TestSubscriberUser.java
  src/test/java/timetables_sort_use_case/interface_adapters/AllTimetablesControllerTest.java
  src/test/java/timetables_sort_use_case/interface_adapters/TestAllTimetablesView.java
  src/test/java/timetables_sort_use_case/interface_adapters/TimetablesSortPresenterTest.java
Labels: enhancement

#87 Use case 1 Feature 13 is... COMPLETE
  build.gradle
  src/main/java/screens/AllTimetablesController.java
  src/main/java/screens/AllTimetablesScreen.java
  src/main/java/screens/SorterController.java
  src/main/java/screens/SorterPresenter.java
  src/main/java/screens/SorterScreen.java
  src/main/java/timetablesSorter_use_case/SorterInputBoundary.java
  src/main/java/timetablesSorter_use_case/SorterInteractor.java
  src/main/java/timetablesSorter_use_case/SorterOutputBoundary.java
  src/main/java/timetablesSorter_use_case/SorterRequestModel.java
  src/main/java/timetablesSorter_use_case/SorterResponseModel.java
  src/main/java/timetablesSorter_use_case/application_business/removeLater.java
  src/main/java/timetablesSorter_use_case/frameworks_and_drivers/removeLater.java
  src/main/java/timetablesSorter_use_case/interface_adapters/removeLater.java
  src/main/java/timetables_sort_use_case/application_business/AllTimetablesInputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/AllTimetablesInteractor.java
  src/main/java/timetables_sort_use_case/application_business/AllTimetablesPublisher.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortInputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortInteractor.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortOutputBoundary.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortRequestModel.java
  src/main/java/timetables_sort_use_case/application_business/TimetablesSortResponseModel.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/AllTimetablesScreen.java
  src/main/java/timetables_sort_use_case/frameworks_and_drivers/TimetablesSortMenu.java
  src/main/java/timetables_sort_use_case/interface_adapters/AllTimetablesController.java
  src/main/java/timetables_sort_use_case/interface_adapters/AllTimetablesView.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortController.java
  src/main/java/timetables_sort_use_case/interface_adapters/TimetablesSortPresenter.java
  src/test/java/edit_timetable_use_case/interface_adapters/TestEditTimetableView.java
  src/test/java/timetables_sort_use_case/application_business/AllTimetablesInteractorTest.java
  src/test/java/timetables_sort_use_case/application_business/TestAllTimetablesInputBoundary.java
  src/test/java/timetables_sort_use_case/application_business/TestSubscriberUser.java
  src/test/java/timetables_sort_use_case/application_business/TestTimetablesSortInputBoundary.java
  src/test/java/timetables_sort_use_case/application_business/TimetablesSortInteractorTest.java
  src/test/java/timetables_sort_use_case/interface_adapters/AllTimetablesControllerTest.java
  src/test/java/timetables_sort_use_case/interface_adapters/TestTimetablesSortPresenter.java
  src/test/java/timetables_sort_use_case/interface_adapters/TimetablesSortControllerTest.java
  src/test/java/timetables_sort_use_case/interface_adapters/TimetablesSortPresenterTest.java
Labels: documentation, enhancement

#93 Updated README.md (Minor)
  README.md
Labels: documentation

#95 8 feature 2 generating with course list
  src/main/java/fileio_use_case/application_business/timetable_specific_classes/TimetableGatewayInteractor.java
  src/test/java/entities/TimetableTest.java
  src/test/java/timetable_generator_use_case/TimeTableGeneratorTest.java
  src/test/java/timetable_generator_use_case/TimetableGeneratorTest.java
Labels: enhancement
